server:
  port: 8888

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:practice
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
      hibernate:
        ddl-auto: create-drop
      generate-ddl: true

      properties:
        format_sql: true
        hibernate:
          show-sql: true

  mvc:
    hiddenmethod:
        filter:
          enable: true

  mustache:
    suffix: .html


logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace

